s = "Key"
print(s[0])
#sto stampando la prima lettera della parola
saluto = "buongiorno"
nome = "vietnam"
messaggio = saluto + " " + nome
print()

numero = 10
nome = "mirko"
s = "ciao, mondo!"
print(len(s))
#non metodo ma funzione che traduce la l stringa in val
print(s.upper())
#metodo che rende il testo maiuscolo
print(s.split('o'))
print(s.split(','))
#separa il testo
carattere = 'A'
#è un carattere

booleanT = True
booleanF = int(False)
#converto il booleano in valore 0
print(booleanT , booleanF)
